import { TemplateType } from "../types";

export const TEMPLATE_REGISTRY: TemplateType[] = [
  {
    id: "ihtiyac-listesi",
    name: "IhtiyacListesi",
    title: "İhtiyaç Listesi",
    category: "1-ihtiyac-tespiti-ve-baslangic",
    description: "Alımı yapılacak mal/hizmet kalemlerinin detaylı ihtiyaç tablosu",
    supportsOlur: false,
    capabilities: {
      supportsOlur: false,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: false,
    },
  },
  {
    id: "ihtiyac-talep-formu",
    name: "IhtiyacTalepFormu",
    title: "İhtiyaç Talep Formu",
    category: "1-ihtiyac-tespiti-ve-baslangic",
    description: "Birimlerin mal/hizmet taleplerini yetkili makama ilettiği resmi form",
    supportsOlur: false,
    capabilities: {
      supportsOlur: false,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: false,
    },
  },
  {
    id: "tasinir-kayit-yetkilisi-gorusu",
    name: "TasinirKayitYetkilisiGorusu",
    title: "Taşınır Kayıt Yetkilisi Görüşü",
    category: "1-ihtiyac-tespiti-ve-baslangic",
    description: "Stokta malzeme bulunup bulunmadığına ilişkin ambar yetkilisi görüşü",
    supportsOlur: false,
    capabilities: {
      supportsOlur: false,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: false,
    },
  },
  {
    id: "teknik-sartname",
    name: "TeknikSartname",
    title: "Teknik Şartname",
    category: "1-ihtiyac-tespiti-ve-baslangic",
    description: "İşin ve malzemelerin teknik kriterlerini belirleyen doküman",
    supportsOlur: false,
    capabilities: {
      supportsOlur: false,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: false,
    },
  },
  {
    id: "luzum-muzekkeresi",
    name: "LuzumMuzekkeresi",
    title: "Lüzum Müzekkeresi",
    category: "1-ihtiyac-tespiti-ve-baslangic",
    description: "Harcama biriminin alım gerekliliğini onaylatan başlangıç müzekkeresi",
    supportsOlur: true,
    capabilities: {
      supportsOlur: true,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: false,
    },
  },
  {
    id: "luzum-muzekkeresi-onay-eki",
    name: "LuzumMuzekkeresiOnayEki",
    title: "Lüzum Müzekkeresi Onay Eki",
    category: "1-ihtiyac-tespiti-ve-baslangic",
    description: "Lüzum müzekkeresine eklenen kalem ve açıklama listesi",
    supportsOlur: false,
    capabilities: {
      supportsOlur: false,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: false,
    },
  },
  {
    id: "luzum-muzekkeresi-teslim-tesellum",
    name: "LuzumMuzekkeresiTeslimTesellum",
    title: "Lüzum Müzekkeresi Teslim Tesellüm",
    category: "1-ihtiyac-tespiti-ve-baslangic",
    description: "Lüzum müzekkeresi teslim alma ve evrak devir tutanağı",
    supportsOlur: false,
    capabilities: {
      supportsOlur: false,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: false,
    },
  },
  {
    id: "harcama-talimati",
    name: "HarcamaTalimati",
    title: "Harcama Talimatı",
    category: "1-ihtiyac-tespiti-ve-baslangic",
    description: "Harcama Yetkilisi tarafından imzalanan alım ve ihale başlatma oluru",
    supportsOlur: true,
    capabilities: {
      supportsOlur: true,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: false,
    },
  },
  {
    id: "komisyon-gorevlendirme-onayi",
    name: "KomisyonGorevlendirmeOnayi",
    title: "Komisyon Görevlendirme Onayı",
    category: "1-ihtiyac-tespiti-ve-baslangic",
    description: "Piyasa Araştırma veya Muayene Kabul Komisyon üyelerinin görevlendirme oluru",
    supportsOlur: true,
    capabilities: {
      supportsOlur: true,
      supportsCommission: true,
      supportedCommissionTypes: ["piyasa_fiyat", "muayene_kabul", "yaklasik_maliyet", "ihale_komisyonu", "all"],
      supportsPersonnelList: true,
      supportsKalemListesi: false,
      supportsFirmaListesi: false,
    },
  },
  {
    id: "komisyon-gorevlendirme-onayi-eki",
    name: "KomisyonGorevlendirmeOnayiEki",
    title: "Komisyon Görevlendirme Onayı Eki",
    category: "1-ihtiyac-tespiti-ve-baslangic",
    description: "Görevlendirilen komisyon üyelerinin detaylı görev dağılım listesi",
    supportsOlur: false,
    capabilities: {
      supportsOlur: false,
      supportsCommission: true,
      supportedCommissionTypes: ["piyasa_fiyat", "muayene_kabul", "yaklasik_maliyet", "ihale_komisyonu", "all"],
      supportsPersonnelList: true,
      supportsKalemListesi: false,
      supportsFirmaListesi: false,
    },
  },
  {
    id: "piyasa-fiyat-arastirma-gorevlendirmesi",
    name: "PiyasaFiyatArastirmaGorevlendirmesi",
    title: "Piyasa Fiyat Araştırma Görevlendirmesi",
    category: "1-ihtiyac-tespiti-ve-baslangic",
    description: "Piyasa fiyat araştırmasını yapmak üzere görevlendirilen personelin olur belgesi",
    supportsOlur: true,
    capabilities: {
      supportsOlur: true,
      supportsCommission: true,
      supportedCommissionTypes: ["piyasa_fiyat", "yaklasik_maliyet"],
      supportsPersonnelList: true,
      supportsKalemListesi: false,
      supportsFirmaListesi: false,
    },
  },
  {
    id: "son-alim-fiyat-cetveli",
    name: "SonAlimFiyatCetveli",
    title: "Son Alım Fiyat Cetveli",
    category: "1-ihtiyac-tespiti-ve-baslangic",
    description: "Geçmiş alımlara ait birim fiyat ve fatura karşılaştırma cetveli",
    supportsOlur: true,
    capabilities: {
      supportsOlur: true,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: false,
    },
  },
  {
    id: "fiyat-arastirma-mektubu",
    name: "FiyatArastirmaMektubu",
    title: "Fiyat Araştırma Mektubu",
    category: "2-piyasa-fiyat-arastirmasi",
    description: "Firmalara teklif sunmaları için gönderilen resmi davet yazısı",
    supportsOlur: false,
    capabilities: {
      supportsOlur: false,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: true,
    },
  },
  {
    id: "birim-fiyat-teklif-mektubu",
    name: "BirimFiyatTeklifMektubu",
    title: "Birim Fiyat Teklif Mektubu",
    category: "2-piyasa-fiyat-arastirmasi",
    description: "Firmaların birim fiyatlarını doldurarak imzaladığı teklif mektubu",
    supportsOlur: false,
    capabilities: {
      supportsOlur: false,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: false,
      supportsKalemListesi: true,
      supportsFirmaListesi: true,
    },
  },
  {
    id: "arastirma-mektubu",
    name: "ArastirmaMektubu",
    title: "Araştırma Mektubu",
    category: "2-piyasa-fiyat-arastirmasi",
    description: "Piyasa araştırması kapsamında gönderilen bilgi ve teklif toplama yazısı",
    supportsOlur: false,
    capabilities: {
      supportsOlur: false,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: true,
    },
  },
  {
    id: "yaklasik-maliyet-cetveli",
    name: "YaklasikMaliyetCetveli",
    title: "Yaklaşık Maliyet Cetveli",
    category: "2-piyasa-fiyat-arastirmasi",
    description: "Toplanan tekliflerden alımın yaklaşık maliyetinin hesaplandığı cetvel",
    supportsOlur: false,
    capabilities: {
      supportsOlur: false,
      supportsCommission: true,
      supportedCommissionTypes: ["piyasa_fiyat", "yaklasik_maliyet"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: true,
    },
  },
  {
    id: "piyasa-fiyat-arastirma-tutanagi",
    name: "PiyasaFiyatArastirmaTutanagi",
    title: "Piyasa Fiyat Araştırma Tutanağı",
    category: "2-piyasa-fiyat-arastirmasi",
    description: "Piyasa fiyat araştırması görevlilerinin teklifleri değerlendirdiği ana tutanak",
    supportsOlur: true,
    capabilities: {
      supportsOlur: true,
      supportsCommission: true,
      supportedCommissionTypes: ["piyasa_fiyat", "yaklasik_maliyet"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: true,
    },
  },
  {
    id: "kabul-edilen-teklif",
    name: "KabulEdilenTeklif",
    title: "Kabul Edilen Teklif Bildirimi",
    category: "3-siparis-ve-sozlesme",
    description: "En avantajlı teklifi veren firmaya yapılan alım kabul bildirimi",
    supportsOlur: false,
    capabilities: {
      supportsOlur: false,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: true,
    },
  },
  {
    id: "dogrudan-temin-onay-belgesi",
    name: "DogrudanTeminOnayBelgesi",
    title: "Doğrudan Temin Onay Belgesi",
    category: "3-siparis-ve-sozlesme",
    description: "Karara bağlanan alımın yetkili makam onay belgesi",
    supportsOlur: true,
    capabilities: {
      supportsOlur: true,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: true,
    },
  },
  {
    id: "butce-sorgusu",
    name: "ButceSorgusu",
    title: "Bütçe Sorgusu ve Ödenek Belgesi",
    category: "3-siparis-ve-sozlesme",
    description: "Alım tutarının ilgili bütçe tertibinden karşılanabilirliğini gösteren form",
    supportsOlur: false,
    capabilities: {
      supportsOlur: false,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: false,
    },
  },
  {
    id: "dogrudan-temin-sozlesmesi",
    name: "DogrudanTeminSozlesmesi",
    title: "Doğrudan Temin Sözleşmesi",
    category: "3-siparis-ve-sozlesme",
    description: "Yüklenici firma ile İdare arasında imzalanan matbu alım sözleşmesi",
    supportsOlur: false,
    capabilities: {
      supportsOlur: false,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: true,
    },
  },
  {
    id: "sozlesmeye-davet",
    name: "SozlesmeyeDavet",
    title: "Sözleşmeye Davet Yazısı",
    category: "3-siparis-ve-sozlesme",
    description: "Kazanan yükleniciye sözleşme imzalaması için iletilen davet yazısı",
    supportsOlur: false,
    capabilities: {
      supportsOlur: false,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: true,
      supportsKalemListesi: false,
      supportsFirmaListesi: true,
    },
  },
  {
    id: "muayene-kabul-komisyonu",
    name: "MuayeneKabulKomisyonu",
    title: "Muayene ve Kabul Komisyon Tutanağı",
    category: "4-kabul-ve-odeme-islemleri",
    description: "Teslim alınan mal veya hizmetin muayene kabul komisyonunca onaylanma tutanağı",
    supportsOlur: true,
    capabilities: {
      supportsOlur: true,
      supportsCommission: true,
      supportedCommissionTypes: ["muayene_kabul"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: false,
    },
  },
  {
    id: "harcama-pusulasi",
    name: "HarcamaPusulasi",
    title: "Harcama Pusulası",
    category: "4-kabul-ve-odeme-islemleri",
    description: "Fatura kesme yükümlülüğü olmayan gerçek kişilerden yapılan alımların tutanağı",
    supportsOlur: false,
    capabilities: {
      supportsOlur: false,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: true,
      supportsKalemListesi: true,
      supportsFirmaListesi: false,
    },
  },
  {
    id: "odeme-yazisi",
    name: "OdemeYazisi",
    title: "Ödeme Yazısı",
    category: "4-kabul-ve-odeme-islemleri",
    description: "Mali hizmetler / muhasebe müdürlüğüne yazılan ödeme üst yazısı",
    supportsOlur: true,
    capabilities: {
      supportsOlur: true,
      supportsCommission: false,
      supportedCommissionTypes: ["none"],
      supportsPersonnelList: true,
      supportsKalemListesi: false,
      supportsFirmaListesi: true,
    },
  },
];